/**
 * Local menu data — real Sheen items from the brand brief.
 * Used as fallback when Supabase is unreachable (paused project,
 * no env vars, demo mode). This lets the menu page render with
 * real products even without a database connection.
 */

export const LOCAL_MENU = [
  {
    id: "cat-mains",
    slug: "mains",
    name: "Mains",
    sort_order: 1,
    menu_items: [
      {
        id: "formal-sheen",
        slug: "formal-sheen",
        name: "Formal Sheen",
        description:
          "Grilled chicken, pickles, garlic sauce and hummus in our house bread",
        price_paisa: 88800,
        image_url: "/images/menu-formal-sheen.png",
        is_popular: true,
        sort_order: 0,
      },
      {
        id: "kf-sheen",
        slug: "kf-sheen",
        name: "KF Sheen",
        description:
          "Battered chicken tenders, pickles, chili mayo, garlic sauce and hummus in our house bread",
        price_paisa: 88800,
        image_url: null,
        is_popular: true,
        sort_order: 1,
      },
      {
        id: "af-sheen",
        slug: "af-sheen",
        name: "AF Sheen",
        description:
          "Grilled chicken and sausage, pickles, chutney, garlic sauce and hummus in our house bread",
        price_paisa: 99900,
        image_url: "/images/menu-af-sheen.png",
        is_popular: true,
        sort_order: 2,
      },
      {
        id: "loaded-sheen",
        slug: "loaded-sheen",
        name: "Loaded Sheen",
        description:
          "Grilled chicken with hummus, garlic sauce and chili mayo, topped with fresh green chutney",
        price_paisa: 88800,
        image_url: null,
        is_popular: false,
        sort_order: 3,
      },
      {
        id: "beef-sheen",
        slug: "beef-sheen",
        name: "Beef Sheen",
        description:
          "Tender beef with pickles, garlic sauce, tahini, chili mayo and fries",
        price_paisa: 122200,
        image_url: "/images/menu-beef-sheen.png",
        is_popular: true,
        sort_order: 4,
      },
      {
        id: "small-a-kf",
        slug: "small-a-kf",
        name: "Small-A KF Sheen",
        description: "Same taste, smaller portion. 6 inch wrap",
        price_paisa: 66600,
        image_url: null,
        is_popular: false,
        sort_order: 5,
      },
      {
        id: "small-a-formal",
        slug: "small-a-formal",
        name: "Small-A Formal Sheen",
        description: "Same taste, smaller portion. 6 inch wrap",
        price_paisa: 66600,
        image_url: null,
        is_popular: false,
        sort_order: 6,
      },
      {
        id: "small-a-af",
        slug: "small-a-af",
        name: "Small-A AF Sheen",
        description: "Same taste, smaller portion. 6 inch wrap",
        price_paisa: 77700,
        image_url: null,
        is_popular: false,
        sort_order: 7,
      },
      {
        id: "small-a-beef",
        slug: "small-a-beef",
        name: "Small-A Beef",
        description: "Same taste, smaller portion. 6 inch wrap",
        price_paisa: 99900,
        image_url: null,
        is_popular: false,
        sort_order: 8,
      },
    ],
  },
  {
    id: "cat-deals",
    slug: "deals",
    name: "Deals Sheels",
    sort_order: 2,
    menu_items: [
      {
        id: "solo-sheen",
        slug: "solo-sheen",
        name: "Solo Sheen",
        description: "Formal or KF Sheen with fries and a drink",
        price_paisa: 122200,
        image_url: null,
        is_popular: false,
        sort_order: 9,
      },
      {
        id: "solo-af",
        slug: "solo-af",
        name: "Solo AF-Sheen",
        description: "AF Sheen with fries and a drink",
        price_paisa: 133300,
        image_url: null,
        is_popular: false,
        sort_order: 10,
      },
      {
        id: "solo-beef",
        slug: "solo-beef",
        name: "Solo Beef Sheen",
        description: "Beef shawarma with fries and a drink",
        price_paisa: 155500,
        image_url: null,
        is_popular: false,
        sort_order: 11,
      },
      {
        id: "double-sawari",
        slug: "double-sawari",
        name: "Double Sawari",
        description: "1 Formal and 1 KF Sheen, 2 fries and 2 drinks",
        price_paisa: 233300,
        image_url: null,
        is_popular: false,
        sort_order: 12,
      },
      {
        id: "teen-batta-sheen",
        slug: "teen-batta-sheen",
        name: "Teen Batta Sheen",
        description:
          "1 Formal, 1 KF and 1 AF Sheen with 3 fries and 3 drinks",
        price_paisa: 355500,
        image_url: null,
        is_popular: false,
        sort_order: 13,
      },
      {
        id: "family-sheen",
        slug: "family-sheen",
        name: "Family Sheen",
        description:
          "1 Formal, 1 KF, 1 AF, 1 Loaded Sheen, 1 loaded fries, 1 hummus and pita, 4 drinks",
        price_paisa: 488800,
        image_url: null,
        is_popular: false,
        sort_order: 14,
      },
      {
        id: "shash-o-panj",
        slug: "shash-o-panj",
        name: "Shash-O-Panj",
        description:
          "1 Formal, 1 KF, 1 AF, 1 Loaded and 1 Beef Sheen with 3 fries and 3 drinks",
        price_paisa: 555500,
        image_url: null,
        is_popular: false,
        sort_order: 15,
      },
    ],
  },
  {
    id: "cat-sides",
    slug: "sides",
    name: "Sides",
    sort_order: 3,
    menu_items: [
      {
        id: "puff-potatoes",
        slug: "puff-potatoes",
        name: "Puff Potatoes",
        description:
          "A mashed potato snack that is golden brown on the outside and soft and fluffy on the inside",
        price_paisa: 35000,
        image_url: null,
        is_popular: true,
        sort_order: 15,
      },
      {
        id: "loaded-fries",
        slug: "loaded-fries",
        name: "Loaded Fries",
        description:
          "Grilled chicken with pickles and jalapenos, garlic sauce and chili mayo on crispy fries",
        price_paisa: 88800,
        image_url: null,
        is_popular: true,
        sort_order: 16,
      },
      {
        id: "hummus-pita",
        slug: "hummus-pita",
        name: "Hummus & Pita",
        description: "Creamy hummus with our house bread",
        price_paisa: 50000,
        image_url: null,
        is_popular: true,
        sort_order: 17,
      },
      {
        id: "saucy-fries",
        slug: "saucy-fries",
        name: "Saucy Fries",
        description: "Our classic fries elevated with house sauces",
        price_paisa: 44400,
        image_url: null,
        is_popular: false,
        sort_order: 18,
      },
      {
        id: "plain-fries",
        slug: "plain-fries",
        name: "Plain Fries",
        description: "Lightly battered fries",
        price_paisa: 33300,
        image_url: null,
        is_popular: true,
        sort_order: 19,
      },
      {
        id: "double-choc-cookie",
        slug: "double-choc-cookie",
        name: "Double Chocolate Cookie",
        description: "Centre filled with molten chocolate",
        price_paisa: 37500,
        image_url: null,
        is_popular: false,
        sort_order: 20,
      },
      {
        id: "choc-chip-cookie",
        slug: "choc-chip-cookie",
        name: "Choco Chip Cookie",
        description: "Something sweet to chase the Sheen",
        price_paisa: 35000,
        image_url: null,
        is_popular: false,
        sort_order: 21,
      },
      {
        id: "limo-soda",
        slug: "limo-soda",
        name: "Limo Soda",
        description: "Our in-house thirst quencher",
        price_paisa: 20000,
        image_url: null,
        is_popular: false,
        sort_order: 22,
      },
      {
        id: "coke",
        slug: "coke",
        name: "Coke",
        description: "300ml bottle",
        price_paisa: 13000,
        image_url: null,
        is_popular: false,
        sort_order: 23,
      },
      {
        id: "sprite",
        slug: "sprite",
        name: "Sprite",
        description: "300ml bottle",
        price_paisa: 13000,
        image_url: null,
        is_popular: false,
        sort_order: 24,
      },
      {
        id: "garlic-sauce",
        slug: "garlic-sauce",
        name: "Garlic Sauce (Toum)",
        description: "A side of our signature garlic sauce",
        price_paisa: 12000,
        image_url: null,
        is_popular: false,
        sort_order: 25,
      },
      {
        id: "chili-mayo",
        slug: "chili-mayo",
        name: "Chili Mayo",
        description: "A side of our tangy chili mayo",
        price_paisa: 12000,
        image_url: null,
        is_popular: false,
        sort_order: 26,
      },
      {
        id: "cheese",
        slug: "cheese",
        name: "Cheese",
        description: "When you want to make your Sheen cheesy",
        price_paisa: 11100,
        image_url: null,
        is_popular: false,
        sort_order: 27,
      },
      {
        id: "jalapeno",
        slug: "jalapeno",
        name: "Jalapeno",
        description: "Make it spicy",
        price_paisa: 5000,
        image_url: null,
        is_popular: false,
        sort_order: 28,
      },
    ],
  },
  {
    id: "cat-ice-cream",
    slug: "ice-cream",
    name: "Ice Cream",
    sort_order: 4,
    menu_items: [
      {
        id: "mango-velvet",
        slug: "mango-velvet",
        name: "Mango Velvet",
        description:
          "Silky smooth mango ice cream crafted from the finest mangoes delivering a rich creamy texture",
        price_paisa: 33300,
        image_url: null,
        is_popular: false,
        sort_order: 29,
      },
      {
        id: "death-by-chocolate",
        slug: "death-by-chocolate",
        name: "Death By Chocolate",
        description:
          "Indulgent chocolate ice cream layered with rich fudge swirls and decadent chocolate chunks",
        price_paisa: 33300,
        image_url: null,
        is_popular: false,
        sort_order: 30,
      },
      {
        id: "mint-choc-chip",
        slug: "mint-choc-chip",
        name: "Mint Chocolate Chip",
        description:
          "Refreshing mint ice cream swirled with rich chocolate chips for a cool creamy treat",
        price_paisa: 33300,
        image_url: null,
        is_popular: false,
        sort_order: 31,
      },
      {
        id: "blueberry-bliss",
        slug: "blueberry-bliss",
        name: "Blueberry Bliss",
        description:
          "Smooth creamy ice cream infused with fresh blueberry flavor",
        price_paisa: 33300,
        image_url: null,
        is_popular: false,
        sort_order: 32,
      },
      {
        id: "lotus-biscoff",
        slug: "lotus-biscoff",
        name: "Lotus Biscoff",
        description:
          "Creamy ice cream infused with the rich caramel and spiced flavor of Lotus Biscoff biscuits",
        price_paisa: 33300,
        image_url: null,
        is_popular: false,
        sort_order: 33,
      },
      {
        id: "key-lime-pie",
        slug: "key-lime-pie",
        name: "Key Lime Pie",
        description:
          "Tangy and refreshing key lime pie ice cream with a crunchy texture and bright citrus flavor",
        price_paisa: 33300,
        image_url: null,
        is_popular: false,
        sort_order: 34,
      },
      {
        id: "strawberry-cheesecake",
        slug: "strawberry-cheesecake",
        name: "Strawberry Cheesecake",
        description:
          "Creamy strawberry cheesecake ice cream blending rich cheesecake flavor with fresh strawberry notes",
        price_paisa: 33300,
        image_url: null,
        is_popular: false,
        sort_order: 35,
      },
    ],
  },
];
